### ISSUE TITLE
📯 Calling out translation providers!

### ISSUE THREAD

**Issue by alexmercerind** [harmonoid/translations#1]
Hi @Lucifer25x, @MickLesk, @0xj0hn, @gaetan1903, @prateekmedia, @KesiTakeshi, @HiSubway, @mi875, @yulog, @c3k4ah, @maisondasilva, @Feelogil, @raitonoberu, @mytja, @TuranBerlin, @ALILEX-1, @zzs20020430, @stonega, @wcxu21.

TL;DR

Your help is needed in translation of app. Please accept invitation in your mail & help me release next update soon!!!
A lot of strings, sentences have been edited, so we need a proper check & your help is required.

<hr></hr>

First of all, thanks a lot for contributing to translations to the project in the past. We're really thankful.
Now finally, we're making our way to support all platforms!

Before this major-major release, your help in translating the app will be really appreciated. 🙇‍♂️
You should've received an invitation on your e-mail for getting ownership of this repository, by which you can edit/change translations without my permissions/involvement. A lot of strings, sentences have been edited, so we need a proper check & your help is required.

I love consistent, cohesive, modern & adaptive design.
And, now finally I feel really confident about the work that I've done.
A lot of time & effort has went into polishing every corner.

Harmonoid supports both local music & YouTube Music! We have advance features like pitch-shifting, volume-boost & speed change, time synced lyrics, permanent playlists, LRC file support, details editor, while still offering a performant good-looking consistent experience. At it's heart, the media library engine that I made & used in Harmonoid is also really performant & bug-free now.

Please checkout project website for more information: [harmonoid.com](https://harmonoid.com).

Attaching few images & videos, for both desktop & mobile...

## Desktop

![](https://github.com/harmonoid/harmonoid/blob/assets/harmonoid_W8Oi1qPZ0O_2.webp?raw=true)
![](https://github.com/harmonoid/harmonoid/blob/assets/harmonoid_MOnywQpgPB_2.webp?raw=true)
![](https://github.com/harmonoid/harmonoid/blob/assets/harmonoid_BRfMT0wIX6_2.webp?raw=true)
![](https://github.com/harmonoid/harmonoid/blob/assets/harmonoid_zZZ1d0yO5G_2.webp?raw=true)
![](https://github.com/harmonoid/harmonoid/blob/assets/harmonoid_yFdqibq6DF_2.webp?raw=true)

## Mobile

|Light|Dark|
|-|-|
| ![0](https://user-images.githubusercontent.com/28951144/187300080-53e60e3d-d322-4b41-b0a4-0519da2e42a2.jpg) | ![0](https://user-images.githubusercontent.com/28951144/187300759-6269d9b7-103c-4de3-bfcb-611304bfa5c7.jpg) |
| ![1](https://user-images.githubusercontent.com/28951144/187300087-5962c3b1-cf52-41a3-a839-8616f1261bfe.jpg) | ![1](https://user-images.githubusercontent.com/28951144/187300767-6f0497b9-5186-4aff-988f-ecfeff0e6b58.jpg) |
| ![2](https://user-images.githubusercontent.com/28951144/187300089-75e4a44a-bf21-48d4-82cf-054bc3749410.jpg) | ![2](https://user-images.githubusercontent.com/28951144/187300771-5254da77-b53e-4f95-8d6d-6a7e81d36dc8.jpg) |
| ![3](https://user-images.githubusercontent.com/28951144/187300091-803f86ec-88e6-422a-8de4-f90dd01c2d10.jpg) | ![3](https://user-images.githubusercontent.com/28951144/187300772-6f16ca4b-b2db-4ccd-bbac-dd07b1819362.jpg) |
| ![4](https://user-images.githubusercontent.com/28951144/187300096-769c4d35-1ff9-4083-9f88-e5c7cbb90e41.jpg) | ![4](https://user-images.githubusercontent.com/28951144/187300776-61eb8bdc-49fb-4c46-9353-be428bc99718.jpg) |
| ![5](https://user-images.githubusercontent.com/28951144/187300100-47c70121-3896-450f-88ed-eaf6b6b781ea.jpg) | ![5](https://user-images.githubusercontent.com/28951144/187300780-f83d4edd-cfee-4bfb-b19b-6cde67847858.jpg) |
| ![6](https://user-images.githubusercontent.com/28951144/187300103-a05b4d6a-eab0-4157-9a7d-cb687763e278.jpg) | ![6](https://user-images.githubusercontent.com/28951144/187300783-e323acbc-09ba-4406-ac75-4a8a09d1e2e2.jpg) |
| ![7](https://user-images.githubusercontent.com/28951144/187300105-45b0ccf6-29b7-4019-bc03-508567bb9fe1.jpg) | ![7](https://user-images.githubusercontent.com/28951144/187300786-f848de9e-5aa8-46a6-9e0c-e44039124c59.jpg) |
| ![8](https://user-images.githubusercontent.com/28951144/187300108-f7c57eae-10e1-4f7b-a882-ae32a506021f.jpg) | ![8](https://user-images.githubusercontent.com/28951144/187300790-67efc600-c256-4188-8ca8-7998971fe4e1.jpg) |
| ![9](https://user-images.githubusercontent.com/28951144/187300112-0434c47b-1531-475d-8f82-8e4ea4b56072.jpg) | ![9](https://user-images.githubusercontent.com/28951144/187300791-b8c4bb09-c374-496a-bbc9-0e328f2022db.jpg) |
| ![10](https://user-images.githubusercontent.com/28951144/187300120-cd184785-b925-46cb-bf19-ef6e3ae6de75.jpg) | ![10](https://user-images.githubusercontent.com/28951144/187300793-3fe34d30-a297-4aa7-819a-4f3d704621d3.jpg) |
| ![0](https://user-images.githubusercontent.com/28951144/187300888-22331e0f-4f1c-483e-b269-a111fbbe5b38.jpg) | ![1](https://user-images.githubusercontent.com/28951144/187300897-2c594a64-da1a-43f2-83f2-b315537d011b.jpg) |

## Animations

And, no UI looks good without proper animations that drives the attention of user while giving a sense of perfection.

We've very strictly followed Material Design guidelines to build the best experience.

See:

https://user-images.githubusercontent.com/28951144/187303518-a3aa717e-fea5-4cbb-8ef4-a646caa66a03.mp4
https://user-images.githubusercontent.com/28951144/187303528-caf288ed-7908-4cad-bc4c-4df1e11c3fa3.mp4
https://user-images.githubusercontent.com/28951144/187303530-0c424db9-6be5-412a-ac4a-4502ff9498eb.mp4

## Spoilers

Since, you guys have helped the project in the past (and I hope you'll in future too), I would like you guys to try out the nightly version of the next release: [Download](https://github.com/harmonoid/nightly/releases/tag/nightly)

**Comment by maisondasilva** [comment]
I have already updated my translation. @alexmercerind

**Comment by alexmercerind** [comment]
Thanks for the kind help!

**Comment by MickLesk** [comment]
Done for Germany 💯 @alexmercerind

**Comment by KesiTakeshi** [comment]
Done for Indonesian!

**Comment by TuranBerlin** [comment]
Done for Turkish ✅
