### ISSUE TITLE
Permanent Maintainer of Spanish (Latin America)

### ISSUE THREAD

**Issue by SteveeWasTaken** [harmonoid/translations#44]
Hi! I would like to permanently maintain the Spanish (Latin America) translation, since I'm the one that updates it whenever it's needed. Thank you.

**Comment by alexmercerind** [comment]
Hi!

First off, thanks a lot for translating the application to your native language. I'm really glad to receive your love & support. I've sent you invitation for this repository, please check your e-mail linked with GitHub account.

Thanks!

**Comment by maisondasilva** [comment]
I'm closing this order if you have not received let us know!
